[versions]
spring = "6.2.19"
springBoot = "3.5.0"
jakartaServlet = "6.0.0"
jakartaAnnotation = "2.1.1"
jackson = "2.18.2"
h2 = "2.3.232"
aspectj = "1.9.25"
junit = "5.11.4"
assertj = "3.26.3"
hamcrest = "2.2"
jsonPath = "2.9.0"
hibernateValidator = "8.0.2.Final"
jakartaEl = "4.0.2"
tomcatEmbed = "10.1.57"
snakeyaml = "2.4"

[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "springBoot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "springBoot" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakartaServlet" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakartaAnnotation" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
aspectjweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonPath" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernateValidator" }
jakarta-el = { module = "org.glassfish:jakarta.el", version.ref = "jakartaEl" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcatEmbed" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
